import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';

// Precache all assets generated by vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache images with a Cache First strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images'
  })
);

// Cache API responses with a Network First strategy
registerRoute(
  ({ request }) => request.destination === 'document' || request.destination === '',
  new NetworkFirst({
    cacheName: 'api-responses'
  })
);